### ISSUE TITLE
isUserless doesn't work properly

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#210] opened 2018-01-07 18:32 UTC
When I first open the app, I `switchToUserless` and when I call `isUserless` it returns true.
However, when I open the app and `switchToUserless` again, all of a sudden `isUserless' now returns false, even though that's not true.

**Examples**

**When app opens for the first time:**
![image](https://user-images.githubusercontent.com/6960329/34652610-fd4e6004-f3e0-11e7-9765-94ac72669533.png)

**Second time:**
![image](https://user-images.githubusercontent.com/6960329/34652618-21d7a00c-f3e1-11e7-945e-a233a9e5772a.png)

Also, because `isUserless` doesn't work properly, my app proceeds to load the account data of the userless account that doesn't exist, and crashes.

Is this how it's supposed to be, since before 1.0.0 `isUserless` always returned true if the app was not authenticated with a user account

**Comment by mattbdean** [comment] 2018-01-07 22:07
Can you post the relevant code?

**Comment by mpivchev** [comment] 2018-01-07 22:09
There isn't anything else besides this

` private static class AuthenticateAsUserlessTask extends AsyncTask<Void, Void, Void> {
        @Override
        protected Void doInBackground(Void... voids) {
            try {
                App.getAccountHelper().switchToUserless();
            } catch (OAuthException e) {
                e.printStackTrace();
            }

            return null;
        }
    }`

**Comment by mattbdean** [comment] 2018-01-07 22:25
Gonna need a bit more context here. When is AuthenticateAsUserlessTask executed? What about hasUser?

**Comment by mpivchev** [comment] 2018-01-07 22:28
I call it on onResume where I authenticate as userless and after that load the user data

```
 @Override
    protected void onResume() {
        super.onResume();
        AccountManager.getInstance().authenticateUserless();
        AccountManager.getInstance().loadUserData();
    }
```

```
 public void loadUserData() {
        new LoadUserDataTask(this).execute();
    }

    /**
     * Fetches user data from Reddit
     */
    private static class LoadUserDataTask extends AsyncTask<Void, Void, Account> {
        private WeakReference<AccountManager> weakAccountManager;

        private LoadUserDataTask(AccountManager weakAccountManager) {
            this.weakAccountManager = new WeakReference<>(weakAccountManager);
        }

        @Override
        protected Account doInBackground(Void... voids) {
            try {
                return App.getAccountHelper().getReddit().me().about();
            } catch (IllegalStateException e) {
                Log.e(TAG, "No user data found, continuing without one");
                return null;
            }
        }

        @Override
        protected void onPostExecute(Account data) {
            if (hasUser()) {
                for (onUserDataReceivedListener l : weakAccountManager.get().listenerList) {
                    l.onUserDataLoaded(data);
                }
            }
        }
    }
```

**Comment by mpivchev** [comment] 2018-01-08 10:57
So, any way to resolve this?

**Comment by mattbdean** [comment] 2018-01-08 15:41
The reason `RedditClient.me()` throws an IllegalStateException is because the [SelfUserReference constructor](https://github.com/mattbdean/JRAW/blob/v1.0.0/lib/src/main/kotlin/net/dean/jraw/references/UserReferences.kt#L111) calls [`RedditClient.requireAuthenticatedUser()`](https://github.com/mattbdean/JRAW/blob/master/lib/src/main/kotlin/net/dean/jraw/RedditClient.kt#L386). This exception only gets thrown when in userless mode.

Since `LoadUserDataTask.doInBackground` returns null to handle IllegalStateExceptions, you can infer that if the Account passed to `onPostExecute` is null, there is no authenticated user.

**Comment by mpivchev** [comment] 2018-01-08 15:43
True, but that doesn't explain why `isUserless` returns false, when clearly the app is in userless mode

**Comment by mattbdean** [comment] 2018-01-08 16:03
Can you log the value of `getAuthMethod()`? Also `Log.e` takes a Throwable as a 3rd parameter, I'm going to need it's message and stacktrace.

**Comment by mpivchev** [comment] 2018-01-09 23:15
Not quite sure what you mean by `Log.e`. Print the stacktrace of what?

Here is what it prints. The Reddit Client tells me that there is a 'userless' user (which I always found odd)

![image](https://user-images.githubusercontent.com/6960329/34748079-2e6ad472-f59b-11e7-878d-6985a09b4e82.png)

**Comment by mattbdean** [comment] 2018-01-10 02:13
I think I've found the issue. When [`switchToUserless`](https://github.com/mattbdean/JRAW/blob/v1.0.0/lib/src/main/kotlin/net/dean/jraw/oauth/AccountHelper.kt#L67) is called, it first tries to see if the TokenStore has an unexpired access token. If it finds one, it creates a new RedditClient with that data. The issue is that when it finds this data, it uses the wrong Credentials to instantiate it:

```kt
return switch(RedditClient(http, current, creds, tokenStore, username))
```

([source](https://github.com/mattbdean/JRAW/blob/v1.0.0/lib/src/main/kotlin/net/dean/jraw/oauth/AccountHelper.kt#L92))

Here `creds` refers to the Credentials originally given to the AccountHelper (with AuthMethod `APP`). It should be using `userlessCreds` (with AuthMethod `USERLESS_APP`) instead.

I should have this fixed by tomorrow.

**Comment by mpivchev** [comment] 2018-01-10 02:45
I think `RedditClient.setAutoRenew` doesn't work properly as well, since it didn't renew the access token automatically when I tried it today, so I'm forced to renew it manually. I will create a new issue tomorrow regarding this after testing a bit more.

**Closed** 2018-01-11 03:13 UTC
Labels: bug

**Comment by mattbdean** [comment] 2018-01-11 03:15
Fixed! To use this patch you can either wait until v1.1.0 or use JitPack:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.mattbdean:JRAW:6977732'
}
```
