### ISSUE TITLE
Exception java.lang.RuntimeException: Unable to parse JSON: {"kind": ......

### ISSUE THREAD

**Issue by jorgegil96** [mattbdean/JRAW#182] opened 2017-04-17 16:47 UTC
Getting a RuntimeException when using the subreddit paginator's next() method caused by a com.fasterxml.jackson.core.JsonParseException.  

I know I can just catch the exception but I thought it might not be the intended behavior for JRAW

```
Exception java.lang.RuntimeException: Unable to parse JSON: {"kind": "Listing", "data": {"modhash": null, "children": [{"kind": "t3", "data": {"contest_mode": false, "banned_by": null, "media_embed": {}, "subreddit": "nba", "selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt......

Caused by com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: was expecting closing quote for a string value
[Source: java.io.StringReader@36ed2b4; line: 1, column: 82295] ()
com.fasterxml.jackson.core.JsonParser._constructError (JsonParser.java:1576)
com.fasterxml.jackson.core.base.ParserMinimalBase._reportError (ParserMinimalBase.java:533)
com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF (ParserMinimalBase.java:470)
com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2 (ReaderBasedJsonParser.java:1760)
com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString (ReaderBasedJsonParser.java:1747)
com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText (ReaderBasedJsonParser.java:233)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:233)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:224)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray (JsonNodeDeserializer.java:270)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:227)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:224)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:224)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray (JsonNodeDeserializer.java:270)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:227)
com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject (JsonNodeDeserializer.java:224)
com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize (JsonNodeDeserializer.java:69)
com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize (JsonNodeDeserializer.java:15)
com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose (ObjectMapper.java:3702)
com.fasterxml.jackson.databind.ObjectMapper.readTree (ObjectMapper.java:2262)
net.dean.jraw.util.JrawUtils.fromString (JrawUtils.java:180)
net.dean.jraw.http.RestResponse.<init> (RestResponse.java:64)
net.dean.jraw.http.OkHttpAdapter.execute (OkHttpAdapter.java:81)
net.dean.jraw.http.RestClient.execute (RestClient.java:120)
net.dean.jraw.RedditClient.execute (RedditClient.java:143)
net.dean.jraw.RedditClient.execute (RedditClient.java:137)
net.dean.jraw.paginators.Paginator.next (Paginator.java:109)
net.dean.jraw.paginators.SubredditPaginator.next (SubredditPaginator.java:51)
com.gmail.jorgegilcavazos.ballislife.network.API.RedditService$11.subscribe (RedditService.java:330)
io.reactivex.internal.operators.single.SingleCreate.subscribeActual (SingleCreate.java:39)
io.reactivex.Single.subscribe (Single.java:2656)
io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete (SingleDelayWithCompletable.java:70)
io.reactivex.internal.disposables.EmptyDisposable.complete (EmptyDisposable.java:67)
io.reactivex.internal.operators.completable.CompletableEmpty.subscribeActual (CompletableEmpty.java:27)
io.reactivex.Completable.subscribe (Completable.java:1592)
io.reactivex.internal.operators.single.SingleDelayWithCompletable.subscribeActual (SingleDelayWithCompletable.java:36)
io.reactivex.Single.subscribe (Single.java:2656)
io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run (SingleSubscribeOn.java:89)
io.reactivex.Scheduler$1.run (Scheduler.java:134)
io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:59)
io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:51)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:269)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```

**Comment by jorgegil96** [comment] 2017-04-17 17:23
Seems like it's not limited to that method and can come from pretty much everywhere if the JrawUtils.fromString method is used.  

Is this intended behavior? Should I be adding try/catch blocks every time I use the API?

**Comment by thatJavaNerd** [comment] 2017-04-18 00:09
No, this is not the intended behavior and you shouldn't have to add try/catch blocks everywhere. Can you post the code you used to get this error?

**Comment by jorgegil96** [comment] 2017-04-18 00:39
Sure, here are a couple that have given me that error:  

```
return Single.create(new SingleOnSubscribe<Listing<Submission>>() {
            @Override
            public void subscribe(SingleEmitter<Listing<Submission>> e) throws Exception {
                RedditClient redditClient = RedditAuthentication.getInstance()
                        .getRedditClient();

                if (redditClient.isAuthenticated()) {

                    try {
                        SubredditPaginator paginator = new SubredditPaginator(redditClient, subreddit);
                        paginator.setLimit(limit);
                        paginator.setSorting(sorting);

                        e.onSuccess(paginator.next(false));  /* thrown here */
                    } catch (Exception ex) {
                        e.onError(ex);
                    }
                } else {
                    e.onError(new NotAuthenticatedException());
                }
            }
        });  


return Single.create(new SingleOnSubscribe<SubscriberCount>() {
            @Override
            public void subscribe(SingleEmitter<SubscriberCount> e) throws Exception {
                RedditClient client = RedditAuthentication.getInstance().getRedditClient();

                try {
                    Subreddit rnba = client.getSubreddit(subreddit); /* thrown here */
                    Long subscribers = rnba.getSubscriberCount();
                    int activeUsers = rnba.getAccountsActive();

                    e.onSuccess(new SubscriberCount(subscribers, activeUsers));
                } catch (Exception ex) {
                    e.onError(ex);
                }
            }
        });
```

**Comment by mattbdean** [comment] 2017-10-09 20:06
Does this issue still persist?

**Comment by jorgegil96** [comment] 2017-10-09 20:21
I'll try to reproduce it

**Comment by zugaldia** [comment] 2017-11-21 10:49
I'm also seeing the same error when using `SubredditPaginator#next`. This is with `v0.9.0` on a server-side app:

```
com.fasterxml.jackson.core.io.JsonEOFException · Unexpected end-of-input: was expecting closing quote for a string value at [Source: java.io.StringReader@10ad37; line: 1, column: 212685]
```
(where the column number varies)

I still haven't been able to reliably reproduce it, but by looking at the server logs, this is something that only happens in a small percentage of invocations. In my case, I'm setting `setLimit(100)`, which is the maximum and, as a consequence, I'm having a larger JSON response from the server. Maybe the response is truncated somewhere and hence the parser fails.

**Comment by mattbdean** [comment] 2017-11-27 01:09
Very strange. I personally haven't run into this issue yet, but what @zugaldia suggests sounds like a fair assessment.

I'm closing this issue because I can't fix anything without a code snippet that can reproduce this exception reliably.

**Closed by mattbdean** 2017-11-27 01:09 UTC
